### ISSUE TITLE
Resampling on Read and Write

### ISSUE THREAD

**Issue by apps4uco** [MeadowlarkDAW/creek#21]
Hi I just came upon creek today, the idea of the buffers and the ability to seek in realtime is excellent.

This may be a massive scope creep, however, for a project I need to do resampling (and looping). 

 I have used https://crates.io/crates/rubato to do sample interpolation in another project.
Would it be possible to create a Decoder/Encoder using rubato as a wrapper to the underlying Codec?

To enable seeking it would be great for there to be 2 different caches. 

I imagine that there could be a pipeline something like

Data in File Format -> Cached Buffers of float -> Cached Resampled data (at different rate) - in chronological order -> Playback sampling (possibly in reverse issue #14, or sample accurate looping)

Is any of this currently possible? 

Thanks

**Comment by apps4uco** [comment]
Sorry, I just saw that you had already addressed resampling in #9, although being able to cache both the decode from disk and also the resampling would be excellent.

**Comment by Be-ing** [comment]
Closing as out of scope
