### ISSUE TITLE
Can we help maintain this library?

### ISSUE THREAD

**Issue by orottier** [MeadowlarkDAW/creek#25]
Hi @BillyDM 

We are happily using this library over at https://github.com/orottier/web-audio-api-rs
We would love to see the open pull requests for creek #22 and #23 merged.
If there is any way we can help share the burden of maintenance, please let us know. We would need to have repository access and publishing rights for crates.io [1] if you are alright with that. Perhaps @Be-ing and/or @uklotzde would like to chime in too?

Thanks!

[1]  https://doc.rust-lang.org/cargo/commands/cargo-owner.html

**Comment by Be-ing** [comment]
I was already thinking of forking this over to Codeberg. Passing the permissions to publish on crates.io would be welcome.

**Comment by BillyDM** [comment]
Actually yeah, I would appreciate some help. I'm up for giving you permissions on both this GitHub repo and crates.io.

Who wants GitHub repo permissions and who wants crates.io permissions?

**Comment by uklotzde** [comment]
@BillyDM That's a very generous offer.

On GitHub you can choose different roles and remain the *Admin* and owner of the repo. This is what I would suggest. I guess all of us qualify as *Maintain*ers considering our experience in open source projects.

Unfortunately, on crates.io the situation is different. The only available role is *Owner* and each owner would be able to kick out any other owner. In the end it is a matter of trust.

**Comment by uklotzde** [comment]
A personal comment: I expect that anyone who stops actively maintaining a repo is willing to give up their granted privileges if no longer needed! This should be a prerequisite when accepting such a grant. It is also good practice from a security point of view.

**Comment by BillyDM** [comment]
Yeah, I'm up for passing on the reigns to someone else.

**Comment by uklotzde** [comment]
@BillyDM My last comment was not directed at you. I was more referring to us who might decide to maintain this library for a while.

Revoking a grant should not be perceived as a personal offense but is actually a necessity under security aspects. Give and take. It's a little bit like deleting code you have written and you were proud of when it is no longer needed ;) To let go is a virtue and evidence of seniority IMHO.

**Comment by orottier** [comment]
Thanks for your understanding @BillyDM 

Perhaps you can give us all three write-priviledges on the repo? Then we can instantiate a policy that all changes must be submitted via PRs and must be approved by the majority of us.

For the crates.io ownership, I'm fine with having it.
Alternatively, you could create a crates.io token for these libs with publish & yank rights at https://crates.io/settings/tokens/new and share it privately with us. We can then use it to set up continuous deployments via https://github.com/google-github-actions/release-please-action

**Comment by BillyDM** [comment]
Alright, I invited @orottier @uklotzde and @Be-ing to write-access on the GitHub repo, and I invited @orottier for access to crates.io.

**Comment by orottier** [comment]
Thanks, looking good!
Great to have this sorted out like this
